spring.application.name=agendaFacil
spring.datasource.url=jdbc:postgresql://localhost:5432/agendaFacil
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


