spring.application.name=agendaFacil
spring.datasource.url=jdbc:postgresql://localhost:5432/agenda
spring.datasource.username=postgres
spring.datasource.password=agenda

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enable=true
spring.flyway.locations=classpath:db/migration


